#!/usr/bin/env bash
#print "Holberton School" 10 times using while loop+ hi before 10

lop=0

while [ $lop -le 10 ]; do
 if [ $lop -eq 9 ]; then
  echo "Best School"
  echo "Hi"
 else
	echo "Best School"
 fi
 ((lop++))
 done
