#!/usr/bin/env bash
# Set initial values
counter=1

# Start a while loop
while [ "$counter" -le 20 ]; do
    case $counter in
        4)
            echo "$counter and then bad luck from China"
            ;;
        9)
            echo "$counter and then bad luck from Japan"
            ;;
        17)
            echo "$counter and then bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac

    # Increment the counter
    ((counter++))
done
