#!/usr/bin/env bash
#!/bin/bash

# Set initial values
counter=1

# Start a while loop
while [ "$counter" -le 20 ]; do
    case $counter in
        5)
            echo -e "bad luck from China.\n$counter"
            ;;
        10)
            echo -e "bad luck from Japan.\n$counter"
            ;;
        18)
            echo -e "bad luck from Italy.\n$counter"
            ;;
        *)
            echo "$counter"
            ;;
    esac

    # Increment the counter
    ((counter++))
done
